framework:
    secret: '%env(APP_SECRET)%'
    session: true

    # Configuration du serializer
    serializer:
        default_context: { groups: ['manga:read'] }  # Définit les groupes de sérialisation par défaut
        mapping:
            paths:
                - '%kernel.project_dir%/src/Entity'  # Emplacement des entités à sérialiser
